name: "Terraform"

on: 
  push:
    branches: ["mnain"]
    paths: ["src/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v6.2.1
        with:
           aws-region: sa-east-1
           aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY_ID }}
